- name: Copy Mongo Repo FIle
  ansible.builtin.template:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB
  ansible.builtin.dnf:
    name: mongodb-org
    state: latest

- name: Edit Mongo Configuration
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongDB Service
  ansible.builtin.systemd_service:
    name: mongod
    enabled: true
    state: restarted
