- name: Disable Nginx Default module
  ansible.builtin.shell: dnf module disable nginx -y 

- name: Enable Nginx 1.24 module
  ansible.builtin.shell: dnf module enable nginx:1.24 -y 

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Setup App Prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name: Copy New Nginx Config FIle
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start Nginx Service
  ansible.builtin.systemd_service:
    name: nginx
    daemon_reload: true
    enabled: true
    state: restarted