- name: Copy Service File
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service
   
- name: Start the Servcie
  ansible.builtin.systemd_service:
    name: "{{ component }}"
    daemon_reload: true
    enabled: true
    state: restarted
    